### ISSUE TITLE
Check that textfiles have \r\n for user files and \n for ini files

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/bananas-api#33]
Most likely this is not the case, but we really should do this.

**Comment by frosch123** [comment]
From TOS:
6.6: changes newlines from .txt files to "DOS" (\r\n) newlines.
6.7: changes newlines from .nut, .obg and .obs files to "unix" (\n) newlines.

Likely ".txt" refers to license/readme/changelog only.
Language files from GS may have a different rule.

**Comment by frosch123** [comment]
Also, it would be cool, if .txt files are checked to be valid UTF-8.

**Comment by TrueBrain** [comment]
All files are already checked for being valid UTF-8 files (either with or without BOM, depending on the file).

**Comment by TrueBrain** [comment]
We currently cannot find a technical reason this is in place, so we suggest to forget about this for now.
