### ISSUE TITLE
/package/<content-type>/<unique-id>/<upload-date> gives 500 for unknown unique-id/upload-date

### ISSUE THREAD

**Issue by frosch123** [OpenTTD/bananas-api#35]
Request:
GET /package/<content-type>/<unique-id>/<upload-date>
with an unknown unique-id or upload-date.

Expected: Response 404

Currently: Response 500

**Comment by TrueBrain** [comment]
I have a hard time reproducing this. Can you give a more complete URL that fails? (as `/package///` works for example).

I have tested several things, but for example `/package/base-graphics/ab/de` returns the (correct) error: `{"message": "unique_id is invalid"}` as a 400.

Or do you have any backtrace I can look at?

**Comment by TrueBrain** [comment]
Ah, found anURL that breaks:
`/package/base-graphics/abcedf12/2020-04-12T14:02:28+00:00`
