### ISSUE TITLE
Increase upload-token expiration time

### ISSUE THREAD

**Issue by frosch123** [OpenTTD/bananas-api#37]
Some content is approaching a size of 1 GB.
With some connections a upload timeout of 15 minutes is rather harsh.

It's also likely that people would start their GB upload, and go for a walk.

So I suggest to make upload-tokens expire together with the session, and not on their own.

**Comment by TrueBrain** [comment]
I think there are two fixes to be made:

Also invalidate uploads when a session expires.
Increase the time an upload expires.
