### ISSUE TITLE
Different packages with same name causes OpenTTD client to mess up

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/bananas-api#56]
It is now possible to rename your package, and as such, people are renaming multiple packages of theirs to the same name.

I have no real problems with this, as the system considers the name a piece of metadata, but it turns out the OpenTTD client has a different vision on this.

When downloading a piece of content with the same name, it appears to be overwriting the existing file. This of course can be considered a bug on its own, but there is also not really a resolution for the client.

I want to suggest to rename the packages to `<uniqueid>-<name>-<version>`. This is still human-readable, and always unique.

**Comment by TrueBrain** [comment]
Assigned you @frosch123 as I would like your opinion; not that you have to make the changes ;)

**Comment by frosch123** [comment]
Looks good. OpenTTD already does something similar in openttd.cfg
> [newgrf]
> 4F472B31|21377D78803A5BB9C57DE4C918A534B3|other/ogfx-trains.grf = 0 14 0 0 1

When unique-id/mdstum are specified, it uses them to look-up GRFs, and ignores the path. Useful when copying configs between machines or sharing profiles.

However, unless already the case, we should definitely enforce unique "version" within each package.

**Comment by TrueBrain** [comment]
Versions have to be unique within a package, that is enforced :)

**Comment by frosch123** [comment]
Fixed via
https://github.com/OpenTTD/bananas-server/commit/a23a30e304b636c6a96819922fd8aa72a8941d3d
